version: 0.2

phases:
  install:
#    runtime-versions:
#      php: 8.2
    commands:
#      - apt-get update -y
#      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#      - apt-get install -y libpq-dev libzip-dev
#      - apt-get install -y php-pgsql
#      - curl -sS https://getcomposer.org/installer -o composer-setup.php
#      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - echo "Installing PHP 8.3..."
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:ondrej/php -y
      - apt-get update -y
      - apt-get install -y php8.3 php8.3-cli php8.3-common php8.3-mbstring php8.3-xml php8.3-mysql php8.3-pgsql php8.3-zip php8.3-bcmath php8.3-curl
      - php -v
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - composer install
      - npm install
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes
